.dashEventCallback_js_metadata <- function() {
deps_metadata <- list(`dash_event_callback` = structure(list(name = "dash_event_callback",
version = "1.2.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-SSE.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashEventCallback",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_event_callback` = structure(list(name = "dash_event_callback",
version = "1.2.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-SSE.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashEventCallback",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_event_callback` = structure(list(name = "dash_event_callback",
version = "1.2.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_event_callback.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashEventCallback",
all_files = FALSE), class = "html_dependency"),
`dash_event_callback` = structure(list(name = "dash_event_callback",
version = "1.2.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_event_callback.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashEventCallback",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
